### ISSUE TITLE
Passer à Google fonts

### ISSUE THREAD

**Issue by AlexandreBourdeaudhui** [O-clock-Alumni/DeviensDev#26]
Actuellement elles font ~120-160Kb selon la fonts. Voir s'il est possible d'ajouter les fonts en `.woff2` afin de rendre les fonts moins lourdes. (~20Kb)

**Comment by webdif** [comment]
On peut faire qu'un seul `link`, en séparant les fonts par `|`
```html
<link href="https://fonts.googleapis.com/css?family=Encode+Sans+Condensed:300,400,500,600,700,800,900|Nunito:300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet" />
```

Ça viendra télécharger uniquement les fonts utilisées par la page.
Niveau perf, on y gagne, car on aura du woff2 (quand le navigateur est compatible).
