### ISSUE TITLE
Page 404 ne s'affiche pas et redirect vers la Home

### ISSUE THREAD

**Issue by AlexandreBourdeaudhui** [O-clock-Alumni/DeviensDev#34]

**Comment by AlexandreBourdeaudhui** [comment]
Possible que ça vienne d'une configuration au niveau de Nginx ?

**Comment by chikamichi** [comment]
Sur la prod donc.

C'est déployé sur Dokku deviensdev-prod, la conf Nginx est dans /home/dokku/deviensdev-prod/nginx.conf et /home/dokku/deviensdev-prod/nginx.conf.d/

Il y a un élément de config à propos des 404 :

``` nginx
error_page 404 /404-error.html;
  location /404-error.html {
    root /var/lib/dokku/data/nginx-vhosts/dokku-errors;
    internal;
  }
```

Mais en pratique, une page non dispo semble 302 vers http://deviensdev.com/ qui 301 (montée en protocole, configurée dans nginx.conf toujours via le plugin Let's Encrypt de Dokku) vers https://deviensdev.com, donc pas vraiment de trace d'une redirection vers /404-error.html => je pense que la 302 est gérée coté client par Gatsby.

**Comment by chikamichi** [comment]
Le coupable probable : https://github.com/KyleAMathews/docker-nginx/blob/master/default#L19 (utilisé par https://github.com/O-clock-Teach/docker-static-nginx-nodejs/blob/master/Dockerfile qui sert l'application Gatsby dans le container deviensdev-prod).

**Comment by AlexandreBourdeaudhui** [comment]
OK depuis le passage sur AWS.
