### ISSUE TITLE
sitemap please :-)

### ISSUE THREAD

**Issue by jpruliere** [O-clock-Alumni/DeviensDev#35]
Si vous avez le temps et une solution simple pour le générer, serait-il possible d'avoir un sitemap ?

@Maylee33 et moi-même sommes en pleine correction et on voudrait éviter de rater une page (même si le site a pas l'air ultra réticulaire non plus).

Et puis, c'est bon pour la SEO :stuck_out_tongue: 

Merci par avance et bravo, j'ai découvert le site hier, il est très chouette et donne envie de lire ses contenus !

**Comment by webdif** [comment]
En attendant : https://www.google.com/search?q=site%3Adeviensdev.com 🙂

**Comment by AlexandreBourdeaudhui** [comment]
Normalement, il y est, le site map, non ? 🤔

**Comment by webdif** [comment]
Ah bah oui en plus : https://deviensdev.com/sitemap.xml
On l'avait même rajouté dans Search Console… Ça m'était sorti de la tête.

**Comment by jpruliere** [comment]
Ok... :man_facepalming:

Merci et désolé !

**Comment by AlexandreBourdeaudhui** [comment]
J'aurais pu fournir le lien directement, mais comme j'étais en déplacement et sur mobile, c'était un peu la galère, sorry !
