### ISSUE TITLE
Preview pull request

### ISSUE THREAD

**Issue by AlexandreBourdeaudhui** [O-clock-Alumni/DeviensDev#43]

**Comment by AlexandreBourdeaudhui** [comment]
J'ai essayé de gérer ça avec Netlify hier soir. Ça devrait fonctionner sans soucis... Mais j'ai rencontré un soucis lors de mes tests qui me « bloque ». En effet lorsqu'on vient connecter le dépôt GitHub à Netlify, il vient mettre en ligne une version « live » qui vient se baser sur `master`.

Plusieurs points : 
- Je n'ai pas trouvé de moyen pour déconnecter cette version live.
- Je n'ai pas si cette version live autoriser les crawlers, à crawler.
- Mettre un password sur cette version live n'est possible qu'à partir d'un plan payant. (https://www.netlify.com/docs/visitor-access-control/)

**Comment by webdif** [comment]
Est-ce qu'on oublierait pas netlify, et on essaie de déployer les PR sur https://deviensdev-preprod.nico.oclock.io ?

**Comment by AlexandreBourdeaudhui** [comment]
> Est-ce qu'on oublierait pas netlify, et on essaie de déployer les PR sur [deviensdev-preprod.nico.oclock.io](https://deviensdev-preprod.nico.oclock.io) ?

Si on fait ça, on vient rendre "public" la preprod du coup ? 🤔 Parce qu'avoir les preview durant les pull-request, c'est leur permettre de voir à quoi va ressembler le site via la contribution 🤔. Il est sûrement possible de mettre en place un hooks afin de déclencher un deploy sur le serveur, mais je n'ai pas encore regardé comment on doit s'y prendre.

**Comment by webdif** [comment]
Si c'est seulement nous qui avons accès, ça me va.
Le contributeur lui, il a surement clone et install en local pour contribuer de toute façon.

**Comment by AlexandreBourdeaudhui** [comment]
> Si c'est seulement l'équipe qui a accès, ça va.
> Le contributeur lui, il a surement clone et install en local pour contribuer de toute façon.

OK je me mets en recherche dès que possible :)
