### ISSUE TITLE
Liste des articles — Titre tronqué 

### ISSUE THREAD

**Issue by AlexandreBourdeaudhui** [O-clock-Alumni/DeviensDev#46]
![shortTitle](https://user-images.githubusercontent.com/24500083/54755590-8a845380-4be6-11e9-913c-00e572b64d7f.png)
<img width="735" alt="Capture d’écran 2019-03-21 à 14 30 18" src="https://user-images.githubusercontent.com/24500083/54755592-8a845380-4be6-11e9-9f1e-45db219e94c8.png">

**Comment by antho005** [comment]
D'ailleurs je viens de tilter mais le titre de l'article ne veut rien dire du tout. La reconversion c'est pas un "moyen" de devenir développeur.
