### ISSUE TITLE
Accepter un avatar autre que celui de GitHub

### ISSUE THREAD

**Issue by AlexandreBourdeaudhui** [O-clock-Alumni/DeviensDev#47]
Afin de ne pas imposer l'avatar GitHub à ceux qui souhaitent contribuer, nous allons faire en sorte d'accepter les avatars "externe", autre que celui qui se trouve sur le profil GitHub.

Pour ce faire, j'ai besoin de savoir comment on compte s'organiser... Trois fois rien, juste quelques détails pour avancer :).

1. Ajouter une propriété supplémentaire (`"avatar"`) dans le fichier `authorX.json` ?

2. Où mettre ces images ? Dans le dossier `authors` ? Dans un autre dossier ?

3. Quelle convention de nommage allons nous adopter pour l'avatar ?

**Comment by webdif** [comment]
Peut-être qu'on peut faire `content/author/images/alexandrebourdeaudhui.png` ?
Si le fichier existe, on le prend. S'il existe pas, on prend l'image GitHub ?
Si c'est casse pied de faire en code "si le fichier existe", on peut ajouter une propriété "avatar" au fichier json ?

**Comment by AlexandreBourdeaudhui** [comment]
> Peut-être qu'on peut faire content/author/images/alexandrebourdeaudhui.png ?

C'est validé !

> Si le fichier existe, on le prend. S'il existe pas, on prend l'image GitHub ?
> Si c'est casse pied de faire en code "si le fichier existe", on peut ajouter une propriété "avatar" au fichier json ?

Je vais voir ce qu'il est possible de faire (par exemple, s'il est possible d'utiliser `fs` avec Gatsby, côté client... Même si ça m'étonnerai 😅), mais j'avais effectivement commencé à ajouter une propriété `avatar` dans le fichier `.json`

**Comment by AlexandreBourdeaudhui** [comment]
Bon, j'ai finalement opté pour la propriété `avatar` dans le fichier `.json`. Plus simple à mettre en place.

Pour information. L'utilisation de fs n'est pas disponible côté client (logique), cependant il est possible de l'utiliser dans `gatsby-node.js`... Cependant, en plus de vérifier si le nom du fichier existe (via l'username ?), il faut également s'assurer que l'extension est la bonne...

Du coup, je suis finalement parti sur quelque chose comme ça : 

```json
// alexandrebourdeaudhui.json

{
  "avatar": "alexandrebourdeaudhui.jpg",
  "twitter": "@qlex_",
  "bio": {
    "short": "Développeur Web",
    "long": "Développeur Web chez O’clock"
  }
}
```

```js
// src/utils/index.js

export const getContributor = async username => {
  ...
  
  // Retrieve data of the contributor, stored in a `.json` file
  const authorData = require(`../../content/authors/${username}`);
  
  const avatar =
    authorData.avatar
      ? require(`../../content/authors/images/${authorData.avatar}`)
      : contributorGithub.avatar;

  ...
}
```

Je pense ajouter une vérification sur le require, au cas où le fichier n'existe pas (faute de frappe, etc...)
